### ISSUE TITLE
Importar dados do modelo de projeto

### ISSUE THREAD

**Issue by viniciussoaresti** [ifpe-cti/demo-lone-survivor#1]
@Jnsb @marcelino05052000 Recomendo baixarem e selecionarem os arquivos relevantes [daqui](https://github.com/ifpe-cti/modelo-projeto-ppo) pra não deixar o repositório vazio e adiantar seu trabalho.

**Comment by viniciussoaresti** [comment]
Recomendo também a criação de labels relevantes para seu projeto (ex.:uma pra cada um de vocês, importância), etc.

**Comment by marcelino05052000** [comment]
Obrigado @viniciussoaresti . Faremos isso o mais breve possível.

**Comment by fabriciofx** [comment]
@viniciussoaresti Parabéns por sua iniciativa de querer ajudar os outros, inclusive os que são dos outros projetos. Precisamos de mais pessoas assim! 👍

**Comment by marcelino05052000** [comment]
@viniciussoaresti acabei de colocar o readme.md no repositório. Essa issue precisa ser fechada agora, já que não é mais necessária. Obrigado.
